### ISSUE TITLE
Deploy to mavenCentral

### ISSUE THREAD

**Issue by asegarra** [lazee/freemarker-java-8#1]
Just to add the requested issue to see this getting deployed to maven central. Thanks for your contribution.

**Comment by gabrielsky** [comment]
when deploy to mavenCentral?

**Comment by heruan** [comment]
I'd like to see it in Maven Central to, since I build from different machines and having it locally breaks the build process.

**Comment by tokuhirom** [comment]
+1 to deploy this to maven central

**Comment by mthmulders** [comment]
Me too. If there's any way we could help, please say so.

**Comment by lazee** [comment]
Hi guys,

I will make it available on Maven Central within a couple of days. Will let you know here when its done.

Best regards,

Jakob

**Comment by tokuhirom** [comment]
great!

**Comment by lazee** [comment]
Version 1.1.2 (Don't ask ;) ) should be available in the Maven Central repository within a day. I had some issues with signing the release on my macbook, but everything is ok now.

**Comment by lazee** [comment]
Since I got your attention here :) https://github.com/amedia/freemarker-java-8/pull/2/files

What do you guys think about merging this PR? Please leave comments.

**Comment by mthmulders** [comment]
Hurray, [it's there](http://search.maven.org/#artifactdetails%7Cno.api.freemarker%7Cfreemarker-java8%7C1.1.2%7Cjar). Thanks @lazee!

**Comment by lazee** [comment]
@mthmulders You're welcome :)
