### ISSUE TITLE
Add support for localized date

### ISSUE THREAD

**Issue by michaelkrog** [lazee/freemarker-java-8#13]
I have a LocalDateTime I want to format as a date for specific locales.

Currently I have to set a specific pattern, but what I really want is to use the formatter from `DateTimeFormatter.ofLocalizedDate(FormatStyle)`. 

So in effect, a DateTimeFormatter created like the following would be great:
```
DateTimeFormatter.ofLocalizedDate(myFormatStyle).withLocale(myLocale);
```

**Comment by lazee** [comment]
@michaelkrog I'm sorry that I haven't replied. For some reason I didn't receive a notification on mail.

But I will make sure to look into it this weekend. Should be fairly easy to fix.

**Comment by lazee** [comment]
@michaelkrog You're saying that you have a LocalDateTime and use `DateTimeFormatter.ofLocalizedDate`.  Shouldn't we be using `DateTimeFormatter.ofLocalizedDateTime` in that scenario?

**Comment by michaelkrog** [comment]
@lazee Yeah, it can be a little confusing.

The api naming is not related to LocalDateTime or LocalTime, but to the style of the returned formatter.

`ofLocalizedDateTime` returns a locale specific date-time formatter for the ISO chronology.  
`ofLocalizedTime` returns a locale specific time format for the ISO chronology.
`ofLocalizedDate` returns a locale specific date format for the ISO chronology.

I am handling all 3 types of formatting here:
https://github.com/michaelkrog/freemarker-java-8/blob/f98fbb100fed42a0b7706c74d60b52efd311ef5d/src/main/java/no/api/freemarker/java8/time/DateTimeTools.java#L75

**Comment by lazee** [comment]
@michaelkrog Nice, but just to be clear: The changes you have made to DateTimeTools solves your needs? Or am I missing out on something here?

**Comment by michaelkrog** [comment]
Yes it does solve my needs. The PR(#14) gives a better explanation of what is actually done in the implementation.

My issue came down to the fact that I often know beforehand what style of format I need but NOT the locale of the output. For example I might need a `FULL` date in a text, but the text can be Danish or English. The `da-DK` format of the date should then be like `Mandag den 4. juni 2018` and the `en-US` something like `Monday, June 4, 2018`. 

#14 makes that possible simply by giving a specific style:  
`${timestamp.format('FULL_DATE')}`

**Comment by michaelkrog** [comment]
Oops.. Reopening again, as it is not closed before the merge has happened.

**Comment by lazee** [comment]
ah, now I get it :) Will look into it tonight.
