### ISSUE TITLE
Fallback to a normal BeanModel if an unrecognized methods is called.

### ISSUE THREAD

**Issue by mihxil** [lazee/freemarker-java-8#18]
I introduced this module when I to provide handier support for java time. Sadly a few existing FTL's got broken which called methods like Instant#toEpochMilli(), and I was actually a bit surprized that those methods disappeared now.

**Comment by mihxil** [comment]
I created a pull request #19

**Comment by lazee** [comment]
@mihxil I'm really sorry that I haven't replied on this earlier. I have started at a new company, and haven't really had the time to look into anything else. I will look at this and come back to you.

**Comment by lazee** [comment]
@mihxil I like this. Could you please resolve the conflict I've introduced with master? Then I will merge it in.

**Comment by lazee** [comment]
Actually I think we should do it with a little twist. I hope it is ok that I take the idea for this and gives you credit in the README file, instead of pulling it in directly (given the conflict)...

**Comment by lazee** [comment]
Will be fixed in #26

**Comment by mihxil** [comment]
Or course, Thanks.

**Comment by lazee** [comment]
2.0.0 just release @mihxil . Available tomorrow from central repo
