### ISSUE TITLE
Maybe instruction in the readme for SpringBoot is a bit outdated

### ISSUE THREAD

**Issue by kortov** [lazee/freemarker-java-8#22]
Hello, I created mcve example https://github.com/kortov/freemarker-java-8-mcve
and in folder config you can check my config that I adapted a bit for a current Spring Boot.

In your readme you write 
`public class FreemarkerConfig extends FreeMarkerAutoConfiguration.FreeMarkerWebConfiguration {`

When in Spring Boot 2.1.4.RELEASE I wrote
`public class FreemarkerConfig extends FreeMarkerAutoConfiguration {`

And I don't see any inner classes in `FreeMarkerAutoConfiguration`

plus I created a constructor, as Intellij Idea suggested it to me
```java
public FreemarkerConfig(ApplicationContext applicationContext, FreeMarkerProperties properties) {
        super(applicationContext, properties);
    }
```

This issue just FYI and I don't see it as a big problem or maybe I'm used your config the wrong way, anyway I guess it could be interesting for you

**Comment by lazee** [comment]
Documentation fixed and linked to this post: https://www.dariawan.com/tutorials/spring/java-8-datetime-freemarker/
