### ISSUE TITLE
Would you like to contribute this work to the FreeMarker core?

### ISSUE THREAD

**Issue by revusky** [lazee/freemarker-java-8#23]
Hi, Jakob. I'm trying to reactivate the FreeMarker project (outside of ASF, long story which I'll tell you if you're interested) and get a FreeMarker 3 out. I am, by the way, to all intents and purposes, the original author.

I ran across this and was wondering if you wanted to just add this newer time/date functionality straight to the FreeMarker core. (And possibly some other things if they occur to you.)

Please feel free to write me at revusky@freemarker.es

**Comment by lazee** [comment]
Cool. I'll contact you by mail.
