### ISSUE TITLE
Add support for default format per time class

### ISSUE THREAD

**Issue by eekboom** [lazee/freemarker-java-8#30]
My use case is a small tool that generates XMLs.
All times should have the format HH:mm:ss
However, by default seconds are only output if non-zero.

So, currently I have to to explicitly include the format everyhwere, so instead of
${startDate} I have to write ${startDate.format("yyyy-MM-dd'T'HH:mm:ss")}
Since I have a lot of LocalDateTime and LocalTime instances, this makes the templates unnecessary long and error prone.

It would be very nice to configure the time adapters to use a specific default formatter!

**Comment by lazee** [comment]
@eekboom Thanks for your feedback. So what you are saying is that you would like a way to override default formats in java code right?. When adding FJ8 to Freemarker.

**Comment by eekboom** [comment]
@lazee Right, that is exactly what I want. I think a separate default format per Java time class would be good, so for example one default format for LocalDateTime and another one for ZonedDateTime.

For a "technical consumer" the current variable time format in LocalDateTime does not make much sense: Currently my import use case works most of the time, but fails if by chance a "second" component happens to be zero (because in that case the default format has no seconds at all).
Since my consumer expects *all* dates and *all* times in a specific format, I'd like to set them once in the freemarker configuration and be done with it.

As a workaround, I currently do this in my templates:

    <#assign DTF="yyyy-MM-dd'T'HH:mm:ss"/>
    <pol:beginn>${begin.format(DTF)}</pol:beginn>

It would be much nicer to be able to configure a default format and then just use 

    <pol:beginn>${beginn}</pol:beginn>

**Comment by lazee** [comment]
https://github.com/lazee/freemarker-java-8/pull/38

@eekboom Took some time :) But here it is. v2.1.0 will be release shortly.

**Comment by lazee** [comment]
Closing issue as release is around the corner.
