### ISSUE TITLE
Setup in Spring Boot via application properties

### ISSUE THREAD

**Issue by hercsoft** [lazee/freemarker-java-8#34]
Another way to setup the Java8ObjectWrapper is via the following property:
```
spring.freemarker.settings.object_wrapper=no.api.freemarker.java8.Java8ObjectWrapper(Configuration.VERSION_2_3_31)
```
This takes advantage of Freemarker Configuration [object builder expressions](https://freemarker.apache.org/docs/api/freemarker/template/Configuration.html#fm_obe)

**Comment by lazee** [comment]
Cool. I will add it to the documentation. Thanks
