### ISSUE TITLE
Jakob, did you receive my email?

### ISSUE THREAD

**Issue by revusky** [lazee/freemarker-java-8#39]
Hi, sorry to use this communication channel a bit inappropriately. But I'm not 100% sure you got my recent email. Maybe it ended up in the SPAM folder. (This has been happening to me a fair bit recently with gmail.) 

I wrote you an email to bring your attention to my recent efforts on the FreeMarker codebase. (Look at https://github.com/freemarker/freemarker3/wiki). We had some email correspondence almost 4 years ago and I had stated my intention to work on this and you seemed interested in it. But 4 years is a lot of water under the bridge. So, if you're not really very interested in FreeMarker at this point, I won't be offended at all. It would be nice to have some clarity on this one way or the other, I guess.

I hope all is going well for you.

**Comment by lazee** [comment]
Hi @revusky!

Sorry for my late reply. Things has been crazy for the last couple of months. I love that you are taking FreeMarker back. As I soon will start working at a new company, I am not sure how much time I would be able to put into this. But I will certainly watch the progress and give some hours to testing and participate whenever I can. 

I also hope things are going well for you.
