### ISSUE TITLE
Add Automatic-Module-Name to JAR Manifest

### ISSUE THREAD

**Issue by vbaidak** [lazee/freemarker-java-8#42]
Hi!

We need this option to be able to use it as a module. See [Gradle Java Library](https://docs.gradle.org/current/userguide/java_library_plugin.html)

**Comment by lazee** [comment]
Sorry for the late reply. I will test and merge the PR in a couple of days. The release should be out within the end of this week.

**Comment by lazee** [comment]
Should be available in the Maven central within a day or so.

**Comment by vbaidak** [comment]
Thank you very much!

**Comment by lazee** [comment]
https://mvnrepository.com/artifact/no.api.freemarker/freemarker-java8/3.0.1
