### ISSUE TITLE
ZoneOffsetAdapter is not used

### ISSUE THREAD

**Issue by martinsefcik** [lazee/freemarker-java-8#6]
ZoneOffset is subclass of ZoneId so it is means that ZoneOffsetAdapter is never used (ZoneIdAdapter is always used for objects of ZoneId and ZoneOffset type)
So the following two ```if``` statements should be in reverted order. (ZoneOffset first)
```java
} else if (obj instanceof ZoneId) {
            return new ZoneIdAdapter((ZoneId) obj);
        } else if (obj instanceof ZoneOffset) {
            return new ZoneOffsetAdapter((ZoneOffset) obj);
}
```

**Comment by lazee** [comment]
Thnx @martinsefcik !

I had some serious issues with releasing to Nexus tonight. Hence the two releases (1.1.3 and 1.1.4). The fix is in version 1.1.4 which will be available in the central repo within a few hours.
